Repository nss-day-cohort-46/rare-rest-rare-api-cool-cake, pull requests merged in 2021-05, with the labels that each got.

#59 Cr tags view
  .gitignore
  .vscode/settings.json
  Rareapi.session.sql
  load_fixtures.sh
  rare/urls.py
  rareapi/migrations/0001_initial.py
  rareapi/migrations/0002_alter_subscription_ended_on.py
  rareapi/models/postreaction.py
  rareapi/models/subscription.py
  rareapi/models/tag.py
  rareapi/models/token.py
  rareapi/views/__init__.py
  rareapi/views/tagSerializer.py
  rareapi/views/tagViewSet.py
Labels: Tags, enhancement

#65 Cr tags create
  rare/urls.py
  rareapi/views/__init__.py
  rareapi/views/tagViewSet.py
Labels: Tags, enhancement

#62 Ap post views create update delete
  rare/urls.py
  rareapi/migrations/0001_initial.py
  rareapi/models/post.py
  rareapi/views/__init__.py
  rareapi/views/auth.py
  rareapi/views/post.py
Labels: Posts, enhancement

#67 feat: user can create categories. Categories are listed alphabetically.
  rare/urls.py
  rareapi/fixtures/categories.json
  rareapi/fixtures/reactions.json
  rareapi/views/__init__.py
  rareapi/views/categorySerializer.py
  rareapi/views/categoryViewSet.py
Labels: Categories, enhancement

#66 Cr categories view
  rareapi/views/categoryViewSet.py
Labels: Categories, enhancement

#70 Dr approve post
  .vscode/settings.json
  rare/urls.py
  rareapi/fixtures/posts.json
  rareapi/views/auth.py
  rareapi/views/post.py
Labels: Posts

#68 feat: user can delete tags.
  rareapi/views/tagViewSet.py
Labels: Categories, enhancement

#71 set filter params for users if staff or not and approved/date
  .vscode/settings.json
  rareapi/views/post.py
Labels: Posts

#76 feat: only staff can delete categories.
  rareapi/views/categoryViewSet.py
Labels: Categories, enhancement

#77 Cr tags edit
  rareapi/views/tagViewSet.py
Labels: Tags, enhancement

#83 Cr categories edit
  rareapi/views/categoryViewSet.py
  rareapi/views/tagViewSet.py
Labels: Categories, enhancement

#80 Cr posts search by tag
  rare.session.sql
  rareapi/views/post.py
Labels: Posts, Tags, enhancement
